### ISSUE TITLE
`ToDo`s not done

### ISSUE THREAD

**Issue by charliefoxtwo** [milotoor/instrument-acs#15]
Nice work on the site! If I ever get around to getting my instrument certification, I'll definitely use it as a reference. Which leads me to...

**Open `<ToDo />` items**
 - [ ] `1.C.k2` IFR Cruising Altitudes https://github.com/milotoor/instrument-acs/blob/252f04a430acdebaff369fd19986d94c5f856fc3/pages/1-preflight-preparation/C-xc-flight-planning.tsx#L302
 - [ ] `2.B.k1c` Electrical System https://github.com/milotoor/instrument-acs/blob/433d4d852597785b12ebec027e7daa68ae2e32a8/pages/2-preflight-procedures/B-instruments.tsx#L197
 - [ ] `5.B.k1` Standard Arrival Procedures https://github.com/milotoor/instrument-acs/blob/433d4d852597785b12ebec027e7daa68ae2e32a8/pages/5-navigation-systems/B-departure-enroute-arrival.tsx#L177
 - [ ] `6.B.k3` Ground-based navigation https://github.com/milotoor/instrument-acs/blob/433d4d852597785b12ebec027e7daa68ae2e32a8/pages/6-approach-procedures/B-precision.tsx#L159
 
 (I'll be honest, I haven't read through the whole site, I just searched for `ToDo` lol)

**Comment by milotoor** [comment]
Hey Tyler! This is great, thanks for putting together an issue! Hopefully I'll get around to filling these in soon (though you are of course welcome to do so too), I just ran out of time before the check ride

**Comment by charliefoxtwo** [comment]
I'm not an instrument student, nor a frontend dev (have you _seen_ the react projects I have on my github? **_shudders_**), nor a proficient writer, so I'm not sure a PR from me would be worth either of our time :D
